// Generated by CoffeeScript 1.10.0

/*
  Generate Release
  Kevin Gravier
  MIT License
 */

(function() {
  var SpawnSync;

  SpawnSync = require('child_process').spawnSync;

  module.exports = function(command_string) {
    var ret;
    ret = SpawnSync('sh', ['-c', command_string], {
      stdio: 'pipe'
    });
    if (ret.error) {
      throw ret.error;
    }
    if (ret.status !== 0) {
      throw new Error("`" + command_string + "` returned " + ret.status + ". \n\n " + (ret.output.toString()));
    }
  };

}).call(this);
