// Generated by CoffeeScript 1.10.0

/*
  Generate Release
  Kevin Gravier
  MIT License
 */

(function() {
  var HelpError, Options, Path, args, bool, existsSync;

  existsSync = require('exists-sync');

  Path = require('path');

  bool = require('@nkcmr/bool');

  HelpError = require('./HelpError');

  args = {
    show_help: ['h', 'help'],
    readme_file_location: ['r', 'readme'],
    package_file_location: ['p', 'package'],
    current_version: ['c', 'current-version'],
    release_type: ['t', 'release-type'],
    no_confirm: ['n', 'no-confirm'],
    skip_git_pull: ['l', 'skip-git-push'],
    skip_git_push: ['s', 'skip-git-push']
  };

  Options = (function() {
    function Options() {}

    Options.prototype.readme_file_location = './README.md';

    Options.prototype.package_file_location = './package.json';

    Options.prototype.no_confirm = false;

    Options.prototype.release_type = null;

    Options.prototype.current_version = null;

    Options.prototype.skip_git_pull = true;

    Options.prototype.skip_git_push = true;

    Options.prototype.validation_error = '\n';

    Options.prototype.parseArgs = function(args) {
      this.args = args;
      if (this.getArgumentValue('show_help')) {
        throw new HelpError;
      }
      this.no_confirm = (this.getArgumentValue('no_confirm')) || this.no_confirm;
      this.skip_git_push = (this.getArgumentValue('skip-git-push')) || this.skip_git_push;
      this.skip_git_pull = (this.getArgumentValue('skip-git-pull')) || this.skip_git_pull;
      this.readme_file_location = Path.resolve((this.getArgumentValue('readme_file_location')) || this.readme_file_location);
      this.package_file_location = Path.resolve((this.getArgumentValue('package_file_location')) || this.package_file_location);
      this.current_version = (this.getArgumentValue('current_version')) || this.current_version;
      this.release_type = (this.getArgumentValue('release_type')) || this.release_type;
      return this.validateArguments();
    };

    Options.prototype.validateArguments = function() {
      var ret;
      ret = true;
      ret &= this.validateReadmeFileLocation();
      ret &= this.validatePackageFileLocation();
      ret &= this.validateReleaseType();
      ret &= this.validateNoConfirm();
      ret &= this.validateSkipGitPull();
      ret &= this.validateSkipGitPush();
      return ret || (function() {
        throw new HelpError(this.validation_error);
      }).call(this);
    };

    Options.prototype.validateReadmeFileLocation = function() {
      if (!existsSync(this.readme_file_location)) {
        this.validation_error += "Readme does not exist: " + this.readme_file_location + "\n";
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.validatePackageFileLocation = function() {
      if (!existsSync(this.package_file_location)) {
        this.validation_error += "Package file does not exist: " + this.package_file_location + "\n";
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.validateCurrentVersion = function() {
      if (!((!this.current_version) || (this.current_version.test(/(\d+\.){2}\d+/)))) {
        this.validation_error += "Invalid current version: " + this.current_version + "\n";
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.validateReleaseType = function() {
      var ref;
      if (!((!this.release_type) || ((ref = this.release_type) === 'patch' || ref === 'minor' || ref === 'major'))) {
        this.validation_error += "Unknown release type: " + this.release_type + "\n";
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.validateNoConfirm = function() {
      if (typeof this.no_confirm !== 'boolean') {
        this.validation_error += 'Invalid value for no-confirm\n';
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.validateSkipGitPush = function() {
      if (typeof this.skip_git_push !== 'boolean') {
        this.validation_error += 'Invalid value for skip-git-push\n';
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.validateSkipGitPull = function() {
      if (typeof this.skip_git_pull !== 'boolean') {
        this.validation_error += 'Invalid value for skip-git-pull\n';
        return false;
      } else {
        return true;
      }
    };

    Options.prototype.getArgumentValue = function(argument) {
      var arg, t;
      t = this;
      return ((function() {
        var i, len, ref, results;
        ref = args[argument];
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          arg = ref[i];
          if (t.args[arg]) {
            results.push(t.args[arg]);
          }
        }
        return results;
      })())[0];
    };

    return Options;

  })();

  module.exports = Options;

}).call(this);
