// Generated by CoffeeScript 1.10.0

/*
Generate Release
Kevin Gravier
MIT License
 */

(function() {
  var PackageFile;

  PackageFile = (function() {
    function PackageFile() {}

    PackageFile.prototype.package_file_location = null;

    PackageFile.prototype.package_file_data = {};

    PackageFile.prototype.load = function(package_file_location) {
      this.package_file_location = package_file_location;
      return this.package_file_data = require(this.package_file_location);
    };

    PackageFile.prototype.save = function() {
      var pack_string;
      pack_string = JSON.stringify(pack, null, 2);
      pack_string += '\n';
      return FS.writeFileSync(this.package_file_location, this.package_file_data, 'utf8');
    };

    PackageFile.prototype.set = function(option, value) {
      var i, len, option_arr, results, s;
      option_arr = option.split('.');
      len = option_arr.length;
      i = 0;
      s = this.package_file_data;
      results = [];
      while (i < len) {
        if (i !== len - 1) {
          results.push(s[option_arr[i]] = value);
        } else {
          results.push(s = s[option_arr[i]]);
        }
      }
      return results;
    };

    PackageFile.prototype.get = function(option) {
      var i, len, option_arr, s;
      option_arr = option.split('.');
      len = option_arr.length;
      i = 0;
      s = this.package_file_data;
      while (i < len) {
        s = s[option_arr[i]];
      }
      return s;
    };

    return PackageFile;

  })();

  module.exports = PackageFile;

}).call(this);
