// Generated by CoffeeScript 1.10.0

/*
  Generate Release
  Kevin Gravier
  MIT License
 */

(function() {
  var ParseSpawnArgs, SpawnSync;

  ParseSpawnArgs = require('parse-spawn-args');

  SpawnSync = require('child_process').spawnSync;

  module.exports = function(command_string) {
    var command, command_array, ret;
    command_array = ParseSpawnArgs.parse(command_string);
    command = command_array.shift();
    ret = SpawnSync(command, command_array, {
      stdio: 'pipe'
    });
    if (ret.error) {
      throw ret.error;
    }
    if (ret.status !== 0) {
      throw new Error("`" + command_string + "` returned " + ret.status + ". \n\n " + (ret.output.toString()));
    }
  };

}).call(this);
