// Generated by CoffeeScript 1.10.0

/*
  Generate Release
  Kevin Gravier
  MIT License
 */

(function() {
  var FS;

  FS = require('fs');

  module.exports = function(package_path, current_version, new_version) {
    var pack, pack_string;
    pack = require(package_path);
    pack.version = new_version;
    pack_string = JSON.stringify(pack, null, 2);
    pack_string += '\n';
    return FS.writeFileSync(package_path, pack_string, 'utf8');
  };

}).call(this);
