// Generated by CoffeeScript 1.10.0

/*
  Generate Release
  Kevin Gravier
  MIT License
 */

(function() {
  var FS;

  FS = require('fs');

  module.exports = function(readme_path, current_version, new_version) {
    var file, new_file;
    file = FS.readFileSync(readme_path);
    new_file = file.toString().replace(current_version, new_version);
    return FS.writeFileSync(readme_path, new_file, 'utf8');
  };

}).call(this);
